### PR TITLE
Pip package

### PR DESCRIPTION
**Pull request by Veerhan-glitch**
For issue #2 

1) install and extract the zip file
2) to conform everything works:
    i) open terminal in the folder contaning the code
   ii) run ``pip install ./``
  iii) run ``python3`` (to basically open python terminal)
   iv) run ``from PythonTrueColor import pokemon``
    v) run ``pokemon.generate()``
    if u get a result, everything works fine

now to publish it,

1) go to [test.pypi.org](https://test.pypi.org/) and register 
2) in your terminal do ``pip install twine``
3) run ``twine upload -r testpypi dist/*``
4) run ``pip uninstall PokemonTrueColor``
5) run ``pip install -i https://test.pypi.org/simple/ PokemonTrueColor`` NOTE replace PokemonTrueColor with the name u want
6) do the " 2) to conform everything works: " step
7) run ``twine upload -r pypi dist/*``

DONE! now u can do uninstall it and install it to see if it works and see it on the pip website also

If u get stuck anywhare fell free to reach out 2 me 

p.s. i will suggest u 2 also watch [How to Build Python Packages for Pip](https://www.youtube.com/watch?v=JkeNVaiUq_c) by James Briggs as that vid was how i learned about it

regards

p.s. do tell when u r done

### CODE REVIEW

**Comment by raffifu** [comment]
Hii, thank you for contributing to this project. I think the structure is good and the instruction is clear. Could you add `.gitignore` file to the repo? You can copy the content from https://github.com/github/gitignore/blob/main/Python.gitignore and save to `.gitignore` on root folder. This file will ignore the compiled file or folder like `__pycache__`

After adding the file you can commit and rebase everything to one commit (to ensure that `__pycache__` is deleted)

**Comment by Veerhan-glitch** [comment]
Ok i will do it as soon as i reach back home

**Comment by raffifu** [comment]
Thank you for quick fix, could you delete the `dist/` folder. I think it will be automatically ignored by git if you rebase/squash into single commit, also ensure that your first commit is not contain `_pycache_`. Because even though you delete it on the next commit, basically the file is still there

**Comment by Veerhan-glitch** [comment]
done, see and check if _pycache_ and dist/ has been removed, also as i have now removed dist/, u will need to create one before publishing, (dist is the one which is basically published),
To do so, run ``python3 -m build``

**Pull request merged**
